### ISSUE TITLE
Error with Remote SDK

### ISSUE THREAD

**Issue by iJackUA** [sirlantis/rubocop-for-rubymine#11]
It works fine when project located on local machine, but when I use Remote SDK and Vagrant dev machine - it throws following error
(I am not sure that Remote SDL  is real issues, but it seems so)
```
null
java.lang.NullPointerException
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.getSdkRoot(RubocopTask.kt:37)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:177)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:55)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:128)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:183)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

OS - both Host and Vagrant - Ubuntu 14.04
RVM - Ruby 2.1.5
Rubocop gem installed on both Host and remote machines.

**Comment by zchee** [comment]
+1

**Comment by amerdidit** [comment]
+1

**Comment by luislew** [comment]
+1

**Comment by yewton** [comment]
+1

**Comment by amerdidit** [comment]
+1

**Comment by amerdidit** [comment]
Seems to be the same issue reported here: https://github.com/sirlantis/rubocop-for-rubymine/issues/19

**Comment by CAMOKPYT** [comment]
+1

**Comment by MOZGIII** [comment]
+1

**Comment by laboone** [comment]
+1

**Comment by m8x** [comment]
+1

**Comment by moskanz** [comment]
+1

**Comment by francoisjacques** [comment]
+1

**Comment by daveallie** [comment]
+1

**Comment by ananevam** [comment]
+1
