### ISSUE TITLE
Exceptions - IndexOutOfBoundsException: Wrong line: #. Available lines count: #

### ISSUE THREAD

**Issue by halilim** [sirlantis/rubocop-for-rubymine#17]
The plugin is throwing IndexOutOfBoundsException exceptions occasionally. Example:

    2015-07-14 06:20:39,306 [2533980]  DEBUG - hub.sirlantis.rubymine.rubocop - Executing RuboCop (SDK=/Users/halil/.rbenv/versions/2.2.1/bin, Bundler=true)/Users/halil/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/bin/bundle exec rubocop --format json /Users/halil/Code/***.html.arb 
    2015-07-14 06:20:39,306 [2533980]   INFO - .ruby.ruby.run.RubyCommandLine - Executing [/Users/halil/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/bin/bundle exec rubocop --format json /Users/halil/Code/***.html.arb], working dir =[/Users/halil/Code/***] 
    2015-07-14 06:20:41,266 [2535940]   WARN - hub.sirlantis.rubymine.rubocop - RuboCop exited with 1 
    2015-07-14 06:20:41,292 [2535966]  ERROR - til.concurrency.QueueProcessor - Wrong line: 38. Available lines count: 38 
    java.lang.IndexOutOfBoundsException: Wrong line: 38. Available lines count: 38
        at com.intellij.openapi.editor.ex.util.SegmentArray.getSegmentEnd(SegmentArray.java:197)
        at com.intellij.openapi.editor.impl.LineSet.getLineEnd(LineSet.java:56)
        at com.intellij.openapi.editor.impl.DocumentImpl.getLineEndOffset(DocumentImpl.java:928)
        at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.createAnnotation(RubocopAnnotator.kt:104)
        at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.apply(RubocopAnnotator.kt:79)
        at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.apply(RubocopAnnotator.kt)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:160)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:45)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1$1.run(ExternalToolPass.java:133)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:127)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
        at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
        at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:695)
        at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
    2015-07-14 06:20:41,294 [2535968]  ERROR - til.concurrency.QueueProcessor - RubyMine 7.1.4  Build #RM-141.1835 
    2015-07-14 06:20:41,294 [2535968]  ERROR - til.concurrency.QueueProcessor - JDK: 1.6.0_65 
    2015-07-14 06:20:41,294 [2535968]  ERROR - til.concurrency.QueueProcessor - VM: Java HotSpot(TM) 64-Bit Server VM 
    2015-07-14 06:20:41,294 [2535968]  ERROR - til.concurrency.QueueProcessor - Vendor: Apple Inc. 
    2015-07-14 06:20:41,294 [2535968]  ERROR - til.concurrency.QueueProcessor - OS: Mac OS X 
    2015-07-14 06:20:41,294 [2535968]  ERROR - til.concurrency.QueueProcessor - Last Action: ReformatCode

**Comment by sirlantis** [comment]
Fixed by 894ff76b8d6517c6dc91c3325fc3a5fd5610c782
