### ISSUE TITLE
Failed to parse Rubocop output

### ISSUE THREAD

**Issue by celsoMartins** [sirlantis/rubocop-for-rubymine#28]
It starts to happen after the upgrade for RubyMine 8.

I've tried to:

1. Remove all my gems and reinstall it.
2. Move the gem from one section to other in Gemfile
3. I have uninstalled the plugin, removed the gem, reinstalled the gem, reinstalled the plugin
4. Completely remove the version 2.2.3 from rbenv and I've reinstalled everything from scratch.

Some screenshots show my environment.

Ruby 2.2.3
Rbenv

Thanks

![image](https://cloud.githubusercontent.com/assets/214322/11760489/ddb2794e-a084-11e5-95ff-9988ad0397a4.png)

![image](https://cloud.githubusercontent.com/assets/214322/11760468/5626b134-a084-11e5-8414-33feae269a9b.png)

![image](https://cloud.githubusercontent.com/assets/214322/11760470/5b5f8bc6-a084-11e5-9609-70301d369197.png)

![image](https://cloud.githubusercontent.com/assets/214322/11760474/6d26d38c-a084-11e5-805b-1203b85a6bc7.png)

**Comment by sirlantis** [comment]
If you do `bundle exec rubocop --format json` manually it works?

**Comment by celsoMartins** [comment]
Yes, it works. It outputs a json with the violations. It also works when I do ```rubocop -R``` in circle ci and in the local terminal. It does not seem a problem in rubocop, but in the plugin for Rubymine.

![image](https://cloud.githubusercontent.com/assets/214322/11767380/dccb3f2a-a192-11e5-9ff3-80c07316fa24.png)

**Comment by tit** [comment]
I have this problem.

System Ruby:
```
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
```

rubocop:
```
0.35.1
```

<img width="489" alt="2015-12-15 17 59 14" src="https://cloud.githubusercontent.com/assets/278604/11814022/aa08a946-a355-11e5-998a-831dcc541533.png">
<img width="549" alt="2015-12-15 17 59 37" src="https://cloud.githubusercontent.com/assets/278604/11814024/aa444118-a355-11e5-8d08-9d9bc4866f94.png">
![2015-12-15 17 59 51](https://cloud.githubusercontent.com/assets/278604/11814023/aa396cca-a355-11e5-8a1a-3d95bd6a3985.png)

**Comment by wtfiwtz** [comment]
I have been reverting to Rubocop 0.32.1 for a few days / weeks to get this to work... is there a log file somewhere?

**Comment by wtfiwtz** [comment]
Ok found `CONTRIBUTING.md`... this is what I get in the log file:

RubyMine 8.0.2 RM-143.1184
JRE 1.8.0_40-release-b105 x86_64
Ruby 2.2.3 MRI
Rubocop 0.35

```
2015-12-17 08:40:50,421 [2586168]   WARN - hub.sirlantis.rubymine.rubocop - Couldn't reset stream 
java.io.IOException: Resetting to invalid mark
	at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.readStreamToString(RubocopTask.kt:143)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.logParseFailure(RubocopTask.kt:115)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:86)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:190)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:60)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:157)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:24)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by wtfiwtz** [comment]
Okay this probably more useful... perhaps its hitting a Unicode BOM and failing to parse in GSON?


```
Nigel-MBP:codethefuture wtfiwtz$ /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/bin/bundle exec rubocop --format json /Developer/codethefuture/app/controllers/application_controller.rb
{"metadata":{"rubocop_version":"0.35.1","ruby_engine":"ruby","ruby_version":"2.2.3","ruby_patchlevel":"173","ruby_platform":"x86_64-darwin15"},"files":[{"path":"app/controllers/application_controller.rb","offenses":[{"severity":"convention","message":"Style/Documentation: Missing top-level class documentation comment.","cop_name":"Style/Documentation","corrected":null,"location":{"line":1,"column":1,"length":5}},{"severity":"convention","message":"Style/SignalException: Use `fail` instead of `raise` to signal exceptions. (https://github.com/bbatsov/ruby-style-guide#fail-method)","cop_name":"Style/SignalException","corrected":false,"location":{"line":18,"column":5,"length":5}},{"severity":"convention","message":"Style/ParenthesesAroundCondition: Don't use parentheses around the condition of an `unless`. (https://github.com/bbatsov/ruby-style-guide#no-parens-if)","cop_name":"Style/ParenthesesAroundCondition","corrected":false,"location":{"line":18,"column":45,"length":35}},{"severity":"warning","message":"Lint/UnusedMethodArgument: Unused method argument - `exception`. If it's necessary, use `_` or `_exception` as an argument name to indicate that it won't be used. You can also write as `user_not_authorized(*)` if you want the method to accept any arguments but don't care about them. (https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars)","cop_name":"Lint/UnusedMethodArgument","corrected":false,"location":{"line":21,"column":27,"length":9}},{"severity":"convention","message":"Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols. (https://github.com/bbatsov/ruby-style-guide#consistent-string-literals)","cop_name":"Style/StringLiterals","corrected":false,"location":{"line":22,"column":21,"length":48}},{"severity":"convention","message":"Style/IndentationConsistency: Inconsistent indentation detected.","cop_name":"Style/IndentationConsistency","corrected":false,"location":{"line":45,"column":5,"length":271}},{"severity":"convention","message":"Metrics/LineLength: Line is too long. [121/120] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)","cop_name":"Metrics/LineLength","corrected":null,"location":{"line":47,"column":121,"length":1}},{"severity":"convention","message":"Style/EmptyLinesAroundClassBody: Extra empty line detected at class body end.","cop_name":"Style/EmptyLinesAroundClassBody","corrected":false,"location":{"line":49,"column":1,"length":1}}]}],"summary":{"offense_count":8,"target_file_count":1,"inspected_file_count":1}
```

```
2015-12-17 08:48:56,779 [3072526]  DEBUG - hub.sirlantis.rubymine.rubocop - Executing RuboCop (SDK=/Users/wtfiwtz/.rvm/rubies/ruby-2.2.3/bin, Bundler=true)/Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/bin/bundle exec rubocop --format json /Developer/codethefuture/app/controllers/application_controller.rb 
2015-12-17 08:48:56,779 [3072526]   INFO - .ruby.ruby.run.RubyCommandLine - Executing [/Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/bin/bundle exec rubocop --format json /Developer/codethefuture/app/controllers/application_controller.rb], working dir =[/Developer/codethefuture] 
2015-12-17 08:48:57,198 [3072945]   WARN - hub.sirlantis.rubymine.rubocop - Failed to parse RuboCop output 
java.io.EOFException: End of input at line 1 column 1
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:553)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:381)
	at io.github.sirlantis.rubymine.rubocop.model.RubocopResult$Companion.readFromJsonReader(RubocopResult.kt:24)
	at io.github.sirlantis.rubymine.rubocop.model.RubocopResult$Companion.readFromReader(RubocopResult.kt:18)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:83)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:190)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:60)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:157)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:24)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by wtfiwtz** [comment]
GSON was changed from 2.2.3 to 2.3.1

This might be relevant:

https://github.com/google/gson/commit/46b73632b0f7591ef1328ee7ddd1e883916fec1e

Otherwise:

https://github.com/google/gson/compare/gson-2.2.3...gson-2.3.1

**Comment by wtfiwtz** [comment]
Ok strangely now it works fine... I just made sure that `bundle install` worked within each project from inside the RubyMine IDE - Ruby 2.2.3 and 2.1.6 MRI both worked okay in the end.

I think there might be some bugs with switching between Ruby versions in RubyMine 8.0 because I've definitely noticed some strange behaviour where I set it to version X on one project and then it reverts to a different version Y.

**Comment by wtfiwtz** [comment]
https://youtrack.jetbrains.com/issue/RUBY-17567

**Comment by tit** [comment]
I do not really understand English. :(
Do I understand correctly that the source of the problem is found?
To solve the problem I need to wait until the new version will come RubyMine, gem Robocop and/or  Robocop PlugIn?

**Comment by sirlantis** [comment]
Thanks @wtfiwtz for looking into this. Let's hope they fix this soon.

**Comment by wtfiwtz** [comment]
@tit @sirlantis turns out my version of ruby configured in RubyMine was being overridden by a `.ruby-version` file so it looks like it all works as expected.

I have seen some high CPU utilisation at times but otherwise it works fine with RubyMine 8.0.2 and rubocop 0.35.1.

**Comment by tit** [comment]
Not worked. :(

![rubymine_001](https://cloud.githubusercontent.com/assets/278604/11991818/cf768ae6-aa2f-11e5-8340-d25b23645326.png)
![rubymine_002](https://cloud.githubusercontent.com/assets/278604/11991819/cf770034-aa2f-11e5-8ef6-fd55112da621.png)
<img width="1151" alt="rubymine_003" src="https://cloud.githubusercontent.com/assets/278604/11991820/cf78fb46-aa2f-11e5-91df-e6ca45e69825.png">

**Comment by wtfiwtz** [comment]
Have you run `bundle install` from rubymine itself (tools menu?) ... have you turned on the logging  (see CONTRIBUTING.md) and what is in your rubymine log file?

**Comment by tit** [comment]
I don't use `budler`, but I do it. `bundle install` from rubymine itself (tools menu?).
[idea.txt](https://github.com/sirlantis/rubocop-for-rubymine/files/71594/idea.txt)

**Comment by wtfiwtz** [comment]
Hi @tit 

Can you run the following from the command line:

    cd /Users/tit/Dropbox/ruwheel
    /usr/bin/ruby rubocop --format json /Users/tit/Dropbox/ruwheel/BitBucket/testing/www/spec/vv-2157_spec.rb

Tell us what output do you see?

**Comment by tit** [comment]
Hi @wtfiwtz 

Yes, I do it, and see next:
```
$ cd /Users/tit/Dropbox/ruwheel
$ /usr/bin/ruby rubocop --format json /Users/tit/Dropbox/ruwheel/BitBucket/testing/www/spec/vv-2157_spec.rb
/usr/bin/ruby: No such file or directory -- rubocop (LoadError)
$ /opt/local/bin/rubocop --format json /Users/tit/Dropbox/ruwheel/BitBucket/testing/www/spec/vv-2157_spec.rb
{
  "metadata":{
    "rubocop_version":"0.35.1",
    "ruby_engine":"ruby",
    "ruby_version":"2.0.0",
    "ruby_patchlevel":"645",
    "ruby_platform":"universal.x86_64-darwin15"
  },
  "files":[
    {
      "path":"BitBucket/testing/www/spec/vv-2157_spec.rb",
      "offenses":[
        {
          "severity":"convention",
          "message":"Use snake_case for source file names.",
          "cop_name":"Style/FileName",
          "corrected":null,
          "location":{
            "line":1,
            "column":1,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Space inside { missing.",
          "cop_name":"Style/SpaceInsideHashLiteralBraces",
          "corrected":false,
          "location":{
            "line":9,
            "column":16,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Space inside } missing.",
          "cop_name":"Style/SpaceInsideHashLiteralBraces",
          "corrected":false,
          "location":{
            "line":9,
            "column":78,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Space inside { missing.",
          "cop_name":"Style/SpaceInsideHashLiteralBraces",
          "corrected":false,
          "location":{
            "line":10,
            "column":15,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Space inside } missing.",
          "cop_name":"Style/SpaceInsideHashLiteralBraces",
          "corrected":false,
          "location":{
            "line":10,
            "column":64,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [88/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":21,
            "column":81,
            "length":8
          }
        },
        {
          "severity":"warning",
          "message":"`(...)` interpreted as grouped expression.",
          "cop_name":"Lint/ParenthesesAsGroupedExpression",
          "corrected":null,
          "location":{
            "line":22,
            "column":13,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [119/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":22,
            "column":81,
            "length":39
          }
        },
        {
          "severity":"warning",
          "message":"`(...)` interpreted as grouped expression.",
          "cop_name":"Lint/ParenthesesAsGroupedExpression",
          "corrected":null,
          "location":{
            "line":23,
            "column":13,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [92/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":23,
            "column":81,
            "length":12
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [88/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":27,
            "column":81,
            "length":8
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [118/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":31,
            "column":81,
            "length":38
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [108/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":37,
            "column":81,
            "length":28
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [107/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":41,
            "column":81,
            "length":27
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [128/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":49,
            "column":81,
            "length":48
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [97/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":50,
            "column":81,
            "length":17
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [81/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":64,
            "column":81,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [123/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":65,
            "column":81,
            "length":43
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [85/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":68,
            "column":81,
            "length":5
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [81/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":69,
            "column":81,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [94/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":83,
            "column":81,
            "length":14
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [87/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":106,
            "column":81,
            "length":7
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [88/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":111,
            "column":81,
            "length":8
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [118/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":115,
            "column":81,
            "length":38
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [108/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":121,
            "column":81,
            "length":28
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [107/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":125,
            "column":81,
            "length":27
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [127/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":133,
            "column":81,
            "length":47
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [81/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":148,
            "column":81,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [123/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":149,
            "column":81,
            "length":43
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [85/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":152,
            "column":81,
            "length":5
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [81/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":153,
            "column":81,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [87/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":194,
            "column":81,
            "length":7
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [88/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":199,
            "column":81,
            "length":8
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [119/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":203,
            "column":81,
            "length":39
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [84/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":204,
            "column":81,
            "length":4
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [107/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":209,
            "column":81,
            "length":27
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [108/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":213,
            "column":81,
            "length":28
          }
        },
        {
          "severity":"warning",
          "message":"`(...)` interpreted as grouped expression.",
          "cop_name":"Lint/ParenthesesAsGroupedExpression",
          "corrected":null,
          "location":{
            "line":214,
            "column":15,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [128/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":221,
            "column":81,
            "length":48
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [97/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":222,
            "column":81,
            "length":17
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [81/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":236,
            "column":81,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [123/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":237,
            "column":81,
            "length":43
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [85/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":240,
            "column":81,
            "length":5
          }
        },
        {
          "severity":"convention",
          "message":"Line is too long. [81/80]",
          "cop_name":"Metrics/LineLength",
          "corrected":null,
          "location":{
            "line":241,
            "column":81,
            "length":1
          }
        },
        {
          "severity":"convention",
          "message":"Final newline missing.",
          "cop_name":"Style/TrailingBlankLines",
          "corrected":false,
          "location":{
            "line":247,
            "column":4,
            "length":0
          }
        }
      ]
    }
  ],
  "summary":{
    "offense_count":45,
    "target_file_count":1,
    "inspected_file_count":1
  }
}
$
```

**Comment by sirlantis** [comment]
Hi everyone, I just pushed 3.1.0 to JetBrains plugin registry which delegates everything to RubyMine's internal handling of Gems/Bundler/RVM/rbenv (found some new APIs in RubyMine 8 which weren't there before). Please create a new issue if the problem persists.

**Comment by celsoMartins** [comment]
Thanks for your effort.

Still not working. I'll open a new issue. =(

![image](https://cloud.githubusercontent.com/assets/214322/12006763/269734a0-abcb-11e5-9fae-bb8de124c803.png)

```12:20:17 PM ProcessNotCreatedException: Failed to run RuboCop command - is it installed? (SDK=/Users/celsomartins/.rvm/rubies/ruby-2.2.2/bin): Cannot run program "rubocop" (in directory "/Users/celsomartins/workspace/crafters/4bricks"): error=2, No such file or directory```

![image](https://cloud.githubusercontent.com/assets/214322/12006767/45162422-abcb-11e5-846d-02816e47ed69.png)

![image](https://cloud.githubusercontent.com/assets/214322/12006768/56ef0e7a-abcb-11e5-98b6-0c2db6792144.png)
