### ISSUE TITLE
Not working with RubyMine 7

### ISSUE THREAD

**Issue by coorasse** [sirlantis/rubocop-for-rubymine#7]
Installed and executed. Can't find anything in the whole project. Looks like it doesn't work with RubyMine7

**Comment by tonycoco** [comment]
Here's the stack trace...

```
Failed to run RuboCop command - is it (or bundler) installed? (SDK=/Users/tonycoco/.rbenv/versions/2.2.0/bin): Cannot run program "bundle" (in directory "/Users/tonycoco/Sites/ember-training/contacts-api"): error=2, No such file or directory
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "bundle" (in directory "/Users/tonycoco/Sites/ember-training/contacts-api"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:290)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt:126)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:58)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:126)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:51)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:134)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:186)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$400(ExternalToolPass.java:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:122)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.io.IOException: Cannot run program "bundle" (in directory "/Users/tonycoco/Sites/ember-training/contacts-api"): error=2, No such file or directory
	at java.lang.ProcessBuilder.processException(ProcessBuilder.java:478)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:300)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:286)
	... 38 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:53)
	at java.lang.ProcessImpl.start(ProcessImpl.java:91)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
	... 40 more
```

**Comment by blotto** [comment]
installed 2.0.0-rc1 with RubyMine7. though does not seem to work

**Comment by sergey-koba-mobidev** [comment]
I confirm the behavior with RubyMine 7.0.4 Can't find anything. Using v2.0.0.rc1

**Comment by giniedp** [comment]
I am running on RubyMine 7.0.4 with the plugin version v2.0.0.rc1 and RVM. It does work for me. 
Do you have a .rubocop.yml file? I'm not sure if that is required but i have one in my projects root folder. Do you get any error or is there just no error showing up? In the latter case try to edit and resave a file and it should then be processed. Rubocop errors should appear.

**Comment by sergey-koba-mobidev** [comment]
Thx, a .rubocop.yml file fixed the problem. I thinks it is required

**Comment by blotto** [comment]
running 7.0.4 as well with .rubocop.yml, but does not work

**Comment by sirlantis** [comment]
@blotto Could you follow the steps in https://github.com/sirlantis/rubocop-for-rubymine/blob/master/CONTRIBUTING.md to get some logging information on the issue?

**Comment by coorasse** [comment]
Adding `.rubocop.yml` and restarting RubyMine worked as well for me.

**Comment by andersennl** [comment]
@coorasse where did you add the `.rubocop.yml`? Was it somewhere else than your home directory?

**Comment by coorasse** [comment]
Not in the Home directory. It was in the project root directory.

**Comment by andersennl** [comment]
Oh I see, thanks for the fast answer @coorasse. But isn't the file supposed to be in the home directory "only"?

**Comment by coorasse** [comment]
No. You can have different configurations for different projects.

**Comment by andersennl** [comment]
Yes that makes sense. Thanks again.
