### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by agross** [sirlantis/rubocop-for-rubymine#9]
On Windows, I get this exception:
```
2015-03-15 23:39:49,116 [  65837]  DEBUG -   io.github.sirlantis.rubymine - Executing RuboCopbundle exec rubocop --format json C:/somewhere/lib/tasks/spec.rake 
2015-03-15 23:39:49,129 [  65850]   INFO - figurations.GeneralCommandLine - Cannot run program "bundle" (in directory "C:/somewhere"): CreateProcess error=2, The system cannot find the file specified 
java.io.IOException: Cannot run program "bundle" (in directory "C:/somewhere"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:300)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:286)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt:126)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:58)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:126)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:51)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:134)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt)
...
```

I used a process logging tool named Process Monitor and found that RubyMine tries to invoke a wide variety of programs, all of which to not exist. These are tried to load from the filesystem for all configured `PATH`s.

* `<path>rubocop.exe`
* `<path>rubocop -format json.exe`
* `<path>rubocop --format json C:/somewhere/lib/tasks/spec.rake`

For example, RubyMine tries to open a file named:

* `C:\Windows\SysWOW64\rubocop.exe`
* `C:\Windows\SysWOW64\rubocop --format json.exe`
* `C:\Windows\SysWOW64\rubocop --format json C:\somewhere\lib\tasks\spec.rake`

It seems you might need to define what program needs to be run a bit differently. I know Windows is very finicky about process and *separate* args. Also note that `.exe` is sometimes appended, while `rubocop` is installed under `<Ruby>\bin\rubocop` and `<Ruby>\bin\rubocop.bat`.

**Comment by snowe2010** [comment]
Ah dang this is a windows specific issue? Shoot. I'm getting this same error.

**Comment by sirlantis** [comment]
This is very weird behavior. But maybe this is just an issue because I failed to release 2.0.0 (which completely uses a different approach to invoking rubocop). Could you try to verifiy if the issue also applies to 2.0.0.rc1 (or 2.0.0, which is should be available through the standard JetBrains Plugin Registry in a few days)?

**Comment by snowe2010** [comment]
I updated to the 2.0.0.rc1 release, but now the plugin does absolutely nothing. No errors, no output, nothing.

**Comment by sirlantis** [comment]
When you mean "no output", does this include log output as described in the following document: https://github.com/sirlantis/rubocop-for-rubymine/blob/master/CONTRIBUTING.md ?

**Comment by snowe2010** [comment]
Didn't see that page, enabled the logs and get this. 

```   
2015-03-31 09:23:42,263 [ 102858]  ERROR - hub.sirlantis.rubymine.rubocop - IntelliJ IDEA 14.1  Build #IU-141.177.4 
2015-03-31 09:23:42,263 [ 102858]  ERROR - hub.sirlantis.rubymine.rubocop - JDK: 1.8.0_31 
2015-03-31 09:23:42,264 [ 102859]  ERROR - hub.sirlantis.rubymine.rubocop - VM: Java HotSpot(TM) Server VM 
2015-03-31 09:23:42,264 [ 102859]  ERROR - hub.sirlantis.rubymine.rubocop - Vendor: Oracle Corporation 
2015-03-31 09:23:42,264 [ 102859]  ERROR - hub.sirlantis.rubymine.rubocop - OS: Windows 7 
2015-03-31 09:23:42,264 [ 102859]  ERROR - hub.sirlantis.rubymine.rubocop - Last Action: EditorRight 
2015-03-31 09:23:44,672 [ 105267]   INFO - r.impl.FileDocumentManagerImpl - reload general_steps.rb from disk? 
2015-03-31 09:23:44,673 [ 105268]   INFO - r.impl.FileDocumentManagerImpl -   documentStamp:20794 
2015-03-31 09:23:44,673 [ 105268]   INFO - r.impl.FileDocumentManagerImpl -   oldFileStamp:0 
2015-03-31 09:23:46,372 [ 106967]  DEBUG - hub.sirlantis.rubymine.rubocop - Executing RuboCop (SDK=C:/tools/ruby215/bin, Bundler=true)C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle exec rubocop --format json C:/Users/tyler.thrailkill/Documents/recondo/tools/watir2_0/trunk/features/step_definitions/general_steps.rb 
2015-03-31 09:23:46,372 [ 106967]   INFO - .ruby.ruby.run.RubyCommandLine - Executing [C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle exec rubocop --format json C:/Users/tyler.thrailkill/Documents/recondo/tools/watir2_0/trunk/features/step_definitions/general_steps.rb], working dir =[C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk] 
2015-03-31 09:23:46,373 [ 106968]   INFO - figurations.GeneralCommandLine - Cannot run program "C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle" (in directory "C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk"): CreateProcess error=193, %1 is not a valid Win32 application 
java.io.IOException: Cannot run program "C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle" (in directory "C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:306)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:292)
	at org.jetbrains.plugins.ruby.ruby.run.RubyCommandLine.createProcess(RubyCommandLine.java:24)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt:179)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:62)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:179)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:55)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:128)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:183)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 39 more
2015-03-31 09:23:46,373 [ 106968]   WARN - hub.sirlantis.rubymine.rubocop - Failed to run RuboCop command 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle" (in directory "C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk"): CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:296)
	at org.jetbrains.plugins.ruby.ruby.run.RubyCommandLine.createProcess(RubyCommandLine.java:24)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt:179)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:62)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:179)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:55)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:128)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:183)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.io.IOException: Cannot run program "C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle" (in directory "C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:306)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:292)
	... 37 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 39 more
2015-03-31 09:23:46,374 [ 106969]  ERROR - hub.sirlantis.rubymine.rubocop - Failed to run RuboCop command - is it (or bundler) installed? (SDK=C:/tools/ruby215/bin) 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle" (in directory "C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk"): CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:296)
	at org.jetbrains.plugins.ruby.ruby.run.RubyCommandLine.createProcess(RubyCommandLine.java:24)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt:179)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask$runViaCommandLine$1.invoke(RubocopTask.kt)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.parseProcessOutput(RubocopTask.kt:62)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.runViaCommandLine(RubocopTask.kt:179)
	at io.github.sirlantis.rubymine.rubocop.RubocopTask.run(RubocopTask.kt:55)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt:128)
	at io.github.sirlantis.rubymine.rubocop.RubocopAnnotator.doAnnotate(RubocopAnnotator.kt)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:183)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.io.IOException: Cannot run program "C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle" (in directory "C:\Users\tyler.thrailkill\Documents\recondo\tools\watir2_0\trunk"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:306)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:292)
	... 37 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 39 more
2015-03-31 09:23:46,375 [ 106970]  ERROR - hub.sirlantis.rubymine.rubocop - IntelliJ IDEA 14.1  Build #IU-141.177.4 
2015-03-31 09:23:46,375 [ 106970]  ERROR - hub.sirlantis.rubymine.rubocop - JDK: 1.8.0_31 
2015-03-31 09:23:46,375 [ 106970]  ERROR - hub.sirlantis.rubymine.rubocop - VM: Java HotSpot(TM) Server VM 
2015-03-31 09:23:46,375 [ 106970]  ERROR - hub.sirlantis.rubymine.rubocop - Vendor: Oracle Corporation 
2015-03-31 09:23:46,375 [ 106970]  ERROR - hub.sirlantis.rubymine.rubocop - OS: Windows 7 
2015-03-31 09:23:46,375 [ 106970]  ERROR - hub.sirlantis.rubymine.rubocop - Last Action: SaveAll 
```

**Comment by sirlantis** [comment]
@snowe2010 Does the mentioned file `C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle` exist? Or would it normally be `C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin\bundle.bat`?

**Comment by snowe2010** [comment]
Yeah the /bin/bundle file exists. I don't think it would usually be .bat, just by looking at my other gems I have installed.

**Comment by sirlantis** [comment]
@snowe2010 Are there any other files in `C:\tools\ruby215\lib\ruby\gems\2.1.0\gems\bundler-1.7.12\bin`?

**Comment by snowe2010** [comment]
Bundle, bundle_ruby, and bundler

![bundle](https://cloud.githubusercontent.com/assets/1534535/6966620/a51f6392-d917-11e4-8e4b-47aa6f0a5e3b.png)

**Comment by lowjoel** [comment]
@sirlantis I've got the same problem, I've debugged this and traced into the source, it's because when Bundle is installed, the Bundle path given is that of the bundle script. This works on Unix environments where arbitrary files can be marked executable and run like a normal program, but this is not possible on Windows.

The fix is to always prepend the entire command line with the Ruby binary so that the script is passed to Ruby to execute. I haven't done much Kotlin (cool language choice!) but it appears that it should not be too difficult to fix.

**Comment by ushastikin** [comment]
@lowjoel your suggestion worked for me (see the attached commit).

p.s. sorry for duplicated commits...

**Comment by lowjoel** [comment]
@ushastikin Maybe you can open a PR?

The path to ruby should not be left to the environment however, because IntelliJ might have multiple Ruby SDKs installed. There should be a way to get the active Ruby SDK and then use the absolute path.

**Comment by ushastikin** [comment]
Agree. I have fixed the ruby binary path.
PR is here https://github.com/sirlantis/rubocop-for-rubymine/pull/21
I have created also a release (with installation file) in case someone wants to use the version with the fix - https://github.com/ushastikin/rubocop-for-rubymine/releases
